### ISSUE TITLE
Repository does not contain PT library

### ISSUE THREAD

**Issue by nayuta-yanagisawa** [Apress/practical-tla-plus#1]
I am now trying to set up the TLA+ toolbox. However, I cannot find the `PT library` in this repository while the book says "*Download the module from https://github.com/Apress/practical-tla-plus*." Could you add the library to the repository?

**Comment by tsenart** [comment]
Yep, +1, also found it missing.

**Comment by rebcabin** [comment]
ditto, blocked in chapter 3, Functions subchapter, uses PT

**Comment by hwayne** [comment]
Now uploaded. Appendix B is also a copy of PT if you have further issues.
