### ISSUE TITLE
Chapter 3 - page 54 

### ISSUE THREAD

**Issue by heidihoward** [Apress/practical-tla-plus#13]
The sentence "Functions ... have no restrictions on recursion" implied to me that operations could not be recursive. However, they can be and here is what ``SumUpTo(n)`` might look like as a recursive operator:

``` 
RECURSIVE SumUpTo(_)
SumUpTo(n) == IF n=0 THEN 0 ELSE n + SumUpTo(n-1) 
```

**Comment by heidihoward** [comment]
This comes up again in PT:
https://github.com/Apress/practical-tla-plus/blob/1afed6f8c95bf921adc948d23d4260d9cd300724/PT/PT.tla#L21

**Comment by hwayne** [comment]
TLA+ operators can be recursive or higher-order, but not both. This matters because `PT!ReduceSet` is higher-order, so needs to use a function in its implementation to get recursion.

**Comment by hwayne** [comment]
Clarified errata.
