### ISSUE TITLE
Chapter 5 - Concurrency: Typos and Questions

### ISSUE THREAD

**Issue by pfeodrippe** [Apress/practical-tla-plus#7]
At page 90 where **Actors** are added to the cache code, in place of `WaitForResources` it should be `UseResources` (or if it's correct with `WaitForResources`, should change the pages before this one).

Great book @hwayne o/ great work

**Comment by pfeodrippe** [comment]
At page 92, the line `when resources_left >= resources_needed;` is really needed?

**Comment by hwayne** [comment]
Fixing in errata
