### ISSUE TITLE
Chapter 2 - Pluscal, Page 33

### ISSUE THREAD

**Issue by heidihoward** [Apress/practical-tla-plus#8]
Chapter 2 - Pluscal, Page 33.

The new macro code should be bold

**Comment by hwayne** [comment]
Thanks for opening all of these! I slotted out mid-November to do all the errata, so even though not much is happening right now, I'm definitely looking at these.

**Comment by heidihoward** [comment]
Thank you for writing the book. It's a great resource! Let me know if you prefer another mechanism for feedback
